[package]
name = "ros-backend"
version = "0.1.0"
edition = "2021"

[lib]
name = "ros_backend"
path = "src/lib.rs"

[dependencies]
rasn-compiler = { path = "../compiler/rasn-compiler" }
regex = "1.10.4"
